// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pnp.proto

/*
Package pnp is a generated protocol buffer package.

It is generated from these files:
	pnp.proto

It has these top-level messages:
	ClientInfo
	CommonClientInfo
	ClientPkgMsg
	ClientPlatformMsg
	InstructionPayload
	CommonServerResponse
	Chunk
	ServerPkgResponse
	ServerPlatformResponse
	Query
	ClientRequestMsg
*/
package pnp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "github.com/PnP/common/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ClientPkgMsgType int32

const (
	ClientPkgMsgType_PKG_NOT_INSTALLED                     ClientPkgMsgType = 0
	ClientPkgMsgType_PKG_INSTALLED                         ClientPkgMsgType = 1
	ClientPkgMsgType_PKG_VERSION_CHANGED                   ClientPkgMsgType = 2
	ClientPkgMsgType_PKG_VERSION_NO_CHANGE                 ClientPkgMsgType = 3
	ClientPkgMsgType_PKG_UNINSTALL_SUCCESS                 ClientPkgMsgType = 4
	ClientPkgMsgType_PKG_UNINSTALL_FAILED                  ClientPkgMsgType = 5
	ClientPkgMsgType_PKG_INSTALL_SUCCESS                   ClientPkgMsgType = 6
	ClientPkgMsgType_PKG_INSTALL_FAILED                    ClientPkgMsgType = 7
	ClientPkgMsgType_PKG_INIT                              ClientPkgMsgType = 8
	ClientPkgMsgType_PKG_GET_FILE                          ClientPkgMsgType = 9
	ClientPkgMsgType_PKG_DOWNLOAD_INSTRUCTION_FILE_SUCCESS ClientPkgMsgType = 10
	ClientPkgMsgType_PKG_DOWNLOAD_INSTRUCTION_FILE_FAILED  ClientPkgMsgType = 11
)

var ClientPkgMsgType_name = map[int32]string{
	0:  "PKG_NOT_INSTALLED",
	1:  "PKG_INSTALLED",
	2:  "PKG_VERSION_CHANGED",
	3:  "PKG_VERSION_NO_CHANGE",
	4:  "PKG_UNINSTALL_SUCCESS",
	5:  "PKG_UNINSTALL_FAILED",
	6:  "PKG_INSTALL_SUCCESS",
	7:  "PKG_INSTALL_FAILED",
	8:  "PKG_INIT",
	9:  "PKG_GET_FILE",
	10: "PKG_DOWNLOAD_INSTRUCTION_FILE_SUCCESS",
	11: "PKG_DOWNLOAD_INSTRUCTION_FILE_FAILED",
}
var ClientPkgMsgType_value = map[string]int32{
	"PKG_NOT_INSTALLED":                     0,
	"PKG_INSTALLED":                         1,
	"PKG_VERSION_CHANGED":                   2,
	"PKG_VERSION_NO_CHANGE":                 3,
	"PKG_UNINSTALL_SUCCESS":                 4,
	"PKG_UNINSTALL_FAILED":                  5,
	"PKG_INSTALL_SUCCESS":                   6,
	"PKG_INSTALL_FAILED":                    7,
	"PKG_INIT":                              8,
	"PKG_GET_FILE":                          9,
	"PKG_DOWNLOAD_INSTRUCTION_FILE_SUCCESS": 10,
	"PKG_DOWNLOAD_INSTRUCTION_FILE_FAILED":  11,
}

func (x ClientPkgMsgType) String() string {
	return proto.EnumName(ClientPkgMsgType_name, int32(x))
}
func (ClientPkgMsgType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ClientPlatformMsgType int32

const (
	ClientPlatformMsgType_PLATFORM_ALREADY_INSTALLED         ClientPlatformMsgType = 0
	ClientPlatformMsgType_PLATFORM_NOT_INSTALLED             ClientPlatformMsgType = 1
	ClientPlatformMsgType_PLATFORM_ARTIFACT_DOWNLOAD_SUCCESS ClientPlatformMsgType = 2
	ClientPlatformMsgType_PLATFORM_ARTIFACT_DOWNLOAD_FAILED  ClientPlatformMsgType = 3
	ClientPlatformMsgType_PLATFORM_DEPLOYMENT_SUCCESS        ClientPlatformMsgType = 4
	ClientPlatformMsgType_PLATFORM_DEPLOYMENT_FAILED         ClientPlatformMsgType = 5
	ClientPlatformMsgType_PLATFORM_INIT                      ClientPlatformMsgType = 6
)

var ClientPlatformMsgType_name = map[int32]string{
	0: "PLATFORM_ALREADY_INSTALLED",
	1: "PLATFORM_NOT_INSTALLED",
	2: "PLATFORM_ARTIFACT_DOWNLOAD_SUCCESS",
	3: "PLATFORM_ARTIFACT_DOWNLOAD_FAILED",
	4: "PLATFORM_DEPLOYMENT_SUCCESS",
	5: "PLATFORM_DEPLOYMENT_FAILED",
	6: "PLATFORM_INIT",
}
var ClientPlatformMsgType_value = map[string]int32{
	"PLATFORM_ALREADY_INSTALLED":         0,
	"PLATFORM_NOT_INSTALLED":             1,
	"PLATFORM_ARTIFACT_DOWNLOAD_SUCCESS": 2,
	"PLATFORM_ARTIFACT_DOWNLOAD_FAILED":  3,
	"PLATFORM_DEPLOYMENT_SUCCESS":        4,
	"PLATFORM_DEPLOYMENT_FAILED":         5,
	"PLATFORM_INIT":                      6,
}

func (x ClientPlatformMsgType) String() string {
	return proto.EnumName(ClientPlatformMsgType_name, int32(x))
}
func (ClientPlatformMsgType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type CmdType int32

const (
	CmdType_RUN        CmdType = 0
	CmdType_CONFIG     CmdType = 1
	CmdType_CLOSE_CONN CmdType = 2
	CmdType_INFO       CmdType = 3
)

var CmdType_name = map[int32]string{
	0: "RUN",
	1: "CONFIG",
	2: "CLOSE_CONN",
	3: "INFO",
}
var CmdType_value = map[string]int32{
	"RUN":        0,
	"CONFIG":     1,
	"CLOSE_CONN": 2,
	"INFO":       3,
}

func (x CmdType) String() string {
	return proto.EnumName(CmdType_name, int32(x))
}
func (CmdType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type PkgOperType int32

const (
	PkgOperType_IS_PKG_INSTALLED      PkgOperType = 0
	PkgOperType_INSTALL_PKG           PkgOperType = 1
	PkgOperType_INSTALL_PKG_FROM_FILE PkgOperType = 2
	PkgOperType_IS_PKG_OUTDATED       PkgOperType = 3
	PkgOperType_UNINSTALL_PKG         PkgOperType = 4
	PkgOperType_GET_NEXT_PKG          PkgOperType = 5
)

var PkgOperType_name = map[int32]string{
	0: "IS_PKG_INSTALLED",
	1: "INSTALL_PKG",
	2: "INSTALL_PKG_FROM_FILE",
	3: "IS_PKG_OUTDATED",
	4: "UNINSTALL_PKG",
	5: "GET_NEXT_PKG",
}
var PkgOperType_value = map[string]int32{
	"IS_PKG_INSTALLED":      0,
	"INSTALL_PKG":           1,
	"INSTALL_PKG_FROM_FILE": 2,
	"IS_PKG_OUTDATED":       3,
	"UNINSTALL_PKG":         4,
	"GET_NEXT_PKG":          5,
}

func (x PkgOperType) String() string {
	return proto.EnumName(PkgOperType_name, int32(x))
}
func (PkgOperType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type SDPOperType int32

const (
	SDPOperType_IS_PLATFORM_INSTALLED      SDPOperType = 0
	SDPOperType_DOWNLOAD_PLATFORM_ARTIFACT SDPOperType = 1
	SDPOperType_DEPLOY_PLATFORM            SDPOperType = 2
)

var SDPOperType_name = map[int32]string{
	0: "IS_PLATFORM_INSTALLED",
	1: "DOWNLOAD_PLATFORM_ARTIFACT",
	2: "DEPLOY_PLATFORM",
}
var SDPOperType_value = map[string]int32{
	"IS_PLATFORM_INSTALLED":      0,
	"DOWNLOAD_PLATFORM_ARTIFACT": 1,
	"DEPLOY_PLATFORM":            2,
}

func (x SDPOperType) String() string {
	return proto.EnumName(SDPOperType_name, int32(x))
}
func (SDPOperType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type ClientInfo struct {
	OsType   string `protobuf:"bytes,1,opt,name=osType" json:"osType,omitempty"`
	OsFlavor string `protobuf:"bytes,2,opt,name=osFlavor" json:"osFlavor,omitempty"`
	ArchType string `protobuf:"bytes,3,opt,name=archType" json:"archType,omitempty"`
	ClientId string `protobuf:"bytes,4,opt,name=clientId" json:"clientId,omitempty"`
}

func (m *ClientInfo) Reset()                    { *m = ClientInfo{} }
func (m *ClientInfo) String() string            { return proto.CompactTextString(m) }
func (*ClientInfo) ProtoMessage()               {}
func (*ClientInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ClientInfo) GetOsType() string {
	if m != nil {
		return m.OsType
	}
	return ""
}

func (m *ClientInfo) GetOsFlavor() string {
	if m != nil {
		return m.OsFlavor
	}
	return ""
}

func (m *ClientInfo) GetArchType() string {
	if m != nil {
		return m.ArchType
	}
	return ""
}

func (m *ClientInfo) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

type CommonClientInfo struct {
	RequestHeader *common.RequestHeader `protobuf:"bytes,1,opt,name=requestHeader" json:"requestHeader,omitempty"`
	ClientInfo    *ClientInfo           `protobuf:"bytes,2,opt,name=clientInfo" json:"clientInfo,omitempty"`
}

func (m *CommonClientInfo) Reset()                    { *m = CommonClientInfo{} }
func (m *CommonClientInfo) String() string            { return proto.CompactTextString(m) }
func (*CommonClientInfo) ProtoMessage()               {}
func (*CommonClientInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CommonClientInfo) GetRequestHeader() *common.RequestHeader {
	if m != nil {
		return m.RequestHeader
	}
	return nil
}

func (m *CommonClientInfo) GetClientInfo() *ClientInfo {
	if m != nil {
		return m.ClientInfo
	}
	return nil
}

type ClientPkgMsg struct {
	CommonClientInfo *CommonClientInfo `protobuf:"bytes,1,opt,name=commonClientInfo" json:"commonClientInfo,omitempty"`
	ClientPkgMsgType ClientPkgMsgType  `protobuf:"varint,2,opt,name=clientPkgMsgType,enum=pnp.ClientPkgMsgType" json:"clientPkgMsgType,omitempty"`
}

func (m *ClientPkgMsg) Reset()                    { *m = ClientPkgMsg{} }
func (m *ClientPkgMsg) String() string            { return proto.CompactTextString(m) }
func (*ClientPkgMsg) ProtoMessage()               {}
func (*ClientPkgMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ClientPkgMsg) GetCommonClientInfo() *CommonClientInfo {
	if m != nil {
		return m.CommonClientInfo
	}
	return nil
}

func (m *ClientPkgMsg) GetClientPkgMsgType() ClientPkgMsgType {
	if m != nil {
		return m.ClientPkgMsgType
	}
	return ClientPkgMsgType_PKG_NOT_INSTALLED
}

type ClientPlatformMsg struct {
	CommonClientInfo      *CommonClientInfo     `protobuf:"bytes,1,opt,name=commonClientInfo" json:"commonClientInfo,omitempty"`
	ClientPlatformMsgType ClientPlatformMsgType `protobuf:"varint,2,opt,name=ClientPlatformMsgType,enum=pnp.ClientPlatformMsgType" json:"ClientPlatformMsgType,omitempty"`
}

func (m *ClientPlatformMsg) Reset()                    { *m = ClientPlatformMsg{} }
func (m *ClientPlatformMsg) String() string            { return proto.CompactTextString(m) }
func (*ClientPlatformMsg) ProtoMessage()               {}
func (*ClientPlatformMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ClientPlatformMsg) GetCommonClientInfo() *CommonClientInfo {
	if m != nil {
		return m.CommonClientInfo
	}
	return nil
}

func (m *ClientPlatformMsg) GetClientPlatformMsgType() ClientPlatformMsgType {
	if m != nil {
		return m.ClientPlatformMsgType
	}
	return ClientPlatformMsgType_PLATFORM_ALREADY_INSTALLED
}

type InstructionPayload struct {
	Cmd []string `protobuf:"bytes,1,rep,name=cmd" json:"cmd,omitempty"`
}

func (m *InstructionPayload) Reset()                    { *m = InstructionPayload{} }
func (m *InstructionPayload) String() string            { return proto.CompactTextString(m) }
func (*InstructionPayload) ProtoMessage()               {}
func (*InstructionPayload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *InstructionPayload) GetCmd() []string {
	if m != nil {
		return m.Cmd
	}
	return nil
}

type CommonServerResponse struct {
	ResponseHeader *common.ResponseHeader `protobuf:"bytes,1,opt,name=responseHeader" json:"responseHeader,omitempty"`
	CmdType        CmdType                `protobuf:"varint,2,opt,name=cmdType,enum=pnp.CmdType" json:"cmdType,omitempty"`
}

func (m *CommonServerResponse) Reset()                    { *m = CommonServerResponse{} }
func (m *CommonServerResponse) String() string            { return proto.CompactTextString(m) }
func (*CommonServerResponse) ProtoMessage()               {}
func (*CommonServerResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CommonServerResponse) GetResponseHeader() *common.ResponseHeader {
	if m != nil {
		return m.ResponseHeader
	}
	return nil
}

func (m *CommonServerResponse) GetCmdType() CmdType {
	if m != nil {
		return m.CmdType
	}
	return CmdType_RUN
}

type Chunk struct {
	FileChunk []byte `protobuf:"bytes,1,opt,name=fileChunk,proto3" json:"fileChunk,omitempty"`
}

func (m *Chunk) Reset()                    { *m = Chunk{} }
func (m *Chunk) String() string            { return proto.CompactTextString(m) }
func (*Chunk) ProtoMessage()               {}
func (*Chunk) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Chunk) GetFileChunk() []byte {
	if m != nil {
		return m.FileChunk
	}
	return nil
}

type ServerPkgResponse struct {
	CommonServerResponse *CommonServerResponse `protobuf:"bytes,1,opt,name=commonServerResponse" json:"commonServerResponse,omitempty"`
	PkgOperType          PkgOperType           `protobuf:"varint,2,opt,name=pkgOperType,enum=pnp.PkgOperType" json:"pkgOperType,omitempty"`
	InstructionPayload   *InstructionPayload   `protobuf:"bytes,3,opt,name=instructionPayload" json:"instructionPayload,omitempty"`
	Chunk                *Chunk                `protobuf:"bytes,4,opt,name=chunk" json:"chunk,omitempty"`
}

func (m *ServerPkgResponse) Reset()                    { *m = ServerPkgResponse{} }
func (m *ServerPkgResponse) String() string            { return proto.CompactTextString(m) }
func (*ServerPkgResponse) ProtoMessage()               {}
func (*ServerPkgResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ServerPkgResponse) GetCommonServerResponse() *CommonServerResponse {
	if m != nil {
		return m.CommonServerResponse
	}
	return nil
}

func (m *ServerPkgResponse) GetPkgOperType() PkgOperType {
	if m != nil {
		return m.PkgOperType
	}
	return PkgOperType_IS_PKG_INSTALLED
}

func (m *ServerPkgResponse) GetInstructionPayload() *InstructionPayload {
	if m != nil {
		return m.InstructionPayload
	}
	return nil
}

func (m *ServerPkgResponse) GetChunk() *Chunk {
	if m != nil {
		return m.Chunk
	}
	return nil
}

type ServerPlatformResponse struct {
	CommonServerResponse *CommonServerResponse `protobuf:"bytes,1,opt,name=commonServerResponse" json:"commonServerResponse,omitempty"`
	SdpOperType          SDPOperType           `protobuf:"varint,2,opt,name=sdpOperType,enum=pnp.SDPOperType" json:"sdpOperType,omitempty"`
	InstructionPayload   *InstructionPayload   `protobuf:"bytes,3,opt,name=instructionPayload" json:"instructionPayload,omitempty"`
}

func (m *ServerPlatformResponse) Reset()                    { *m = ServerPlatformResponse{} }
func (m *ServerPlatformResponse) String() string            { return proto.CompactTextString(m) }
func (*ServerPlatformResponse) ProtoMessage()               {}
func (*ServerPlatformResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ServerPlatformResponse) GetCommonServerResponse() *CommonServerResponse {
	if m != nil {
		return m.CommonServerResponse
	}
	return nil
}

func (m *ServerPlatformResponse) GetSdpOperType() SDPOperType {
	if m != nil {
		return m.SdpOperType
	}
	return SDPOperType_IS_PLATFORM_INSTALLED
}

func (m *ServerPlatformResponse) GetInstructionPayload() *InstructionPayload {
	if m != nil {
		return m.InstructionPayload
	}
	return nil
}

type Query struct {
}

func (m *Query) Reset()                    { *m = Query{} }
func (m *Query) String() string            { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()               {}
func (*Query) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type ClientRequestMsg struct {
	RequestHeader *common.RequestHeader `protobuf:"bytes,1,opt,name=RequestHeader" json:"RequestHeader,omitempty"`
	QueryData     *Query                `protobuf:"bytes,2,opt,name=QueryData" json:"QueryData,omitempty"`
}

func (m *ClientRequestMsg) Reset()                    { *m = ClientRequestMsg{} }
func (m *ClientRequestMsg) String() string            { return proto.CompactTextString(m) }
func (*ClientRequestMsg) ProtoMessage()               {}
func (*ClientRequestMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ClientRequestMsg) GetRequestHeader() *common.RequestHeader {
	if m != nil {
		return m.RequestHeader
	}
	return nil
}

func (m *ClientRequestMsg) GetQueryData() *Query {
	if m != nil {
		return m.QueryData
	}
	return nil
}

func init() {
	proto.RegisterType((*ClientInfo)(nil), "pnp.ClientInfo")
	proto.RegisterType((*CommonClientInfo)(nil), "pnp.CommonClientInfo")
	proto.RegisterType((*ClientPkgMsg)(nil), "pnp.ClientPkgMsg")
	proto.RegisterType((*ClientPlatformMsg)(nil), "pnp.ClientPlatformMsg")
	proto.RegisterType((*InstructionPayload)(nil), "pnp.InstructionPayload")
	proto.RegisterType((*CommonServerResponse)(nil), "pnp.CommonServerResponse")
	proto.RegisterType((*Chunk)(nil), "pnp.Chunk")
	proto.RegisterType((*ServerPkgResponse)(nil), "pnp.ServerPkgResponse")
	proto.RegisterType((*ServerPlatformResponse)(nil), "pnp.ServerPlatformResponse")
	proto.RegisterType((*Query)(nil), "pnp.Query")
	proto.RegisterType((*ClientRequestMsg)(nil), "pnp.ClientRequestMsg")
	proto.RegisterEnum("pnp.ClientPkgMsgType", ClientPkgMsgType_name, ClientPkgMsgType_value)
	proto.RegisterEnum("pnp.ClientPlatformMsgType", ClientPlatformMsgType_name, ClientPlatformMsgType_value)
	proto.RegisterEnum("pnp.CmdType", CmdType_name, CmdType_value)
	proto.RegisterEnum("pnp.PkgOperType", PkgOperType_name, PkgOperType_value)
	proto.RegisterEnum("pnp.SDPOperType", SDPOperType_name, SDPOperType_value)
}

func init() { proto.RegisterFile("pnp.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 990 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xcb, 0x6e, 0xdb, 0x46,
	0x14, 0x35, 0x25, 0xbf, 0x74, 0xe5, 0x07, 0x75, 0x63, 0x2b, 0xb6, 0x52, 0xa4, 0x2e, 0x51, 0x1b,
	0xaa, 0x17, 0x76, 0xe1, 0x6e, 0x0a, 0x04, 0x08, 0x40, 0x90, 0x94, 0x42, 0x44, 0x26, 0xd9, 0x21,
	0xdd, 0x36, 0x8b, 0x82, 0x60, 0x28, 0x5a, 0x16, 0x2c, 0x91, 0x2c, 0x25, 0x05, 0xd5, 0xa6, 0x68,
	0x97, 0xdd, 0x17, 0xfd, 0x86, 0xfe, 0x4b, 0x7f, 0xa3, 0xdf, 0xd0, 0x75, 0x31, 0xc3, 0xd7, 0xe8,
	0xd1, 0x00, 0x05, 0x92, 0x9d, 0xe6, 0x9e, 0x73, 0xcf, 0x9c, 0x39, 0x33, 0x9c, 0x11, 0xd4, 0xe2,
	0x30, 0xbe, 0x8a, 0x93, 0x68, 0x1a, 0x61, 0x35, 0x0e, 0xe3, 0x56, 0x7b, 0x30, 0x9c, 0x3e, 0xcc,
	0xde, 0x5e, 0xf9, 0xd1, 0xf8, 0xda, 0x0a, 0xad, 0x6b, 0x3f, 0x1a, 0x8f, 0xa3, 0xf0, 0x9a, 0x31,
	0xb2, 0x41, 0x4a, 0x97, 0x7e, 0x02, 0x50, 0x46, 0xc3, 0x20, 0x9c, 0xea, 0xe1, 0x7d, 0x84, 0x4d,
	0xd8, 0x8e, 0x26, 0xce, 0x3c, 0x0e, 0x4e, 0x84, 0x33, 0xa1, 0x5d, 0x23, 0xd9, 0x08, 0x5b, 0xb0,
	0x1b, 0x4d, 0x3a, 0x23, 0xef, 0x5d, 0x94, 0x9c, 0x54, 0x18, 0x52, 0x8c, 0x29, 0xe6, 0x25, 0xfe,
	0x03, 0xeb, 0xaa, 0xa6, 0x58, 0x3e, 0xa6, 0x98, 0x9f, 0xaa, 0xf7, 0x4f, 0x36, 0x53, 0x2c, 0x1f,
	0x4b, 0xbf, 0x08, 0x20, 0x2a, 0xcc, 0x0a, 0x67, 0xe0, 0x05, 0xec, 0x27, 0xc1, 0x8f, 0xb3, 0x60,
	0x32, 0x7d, 0x15, 0x78, 0xfd, 0x20, 0x61, 0x3e, 0xea, 0x37, 0xc7, 0x57, 0x99, 0x69, 0xc2, 0x83,
	0x64, 0x91, 0x8b, 0xd7, 0x00, 0x7e, 0x21, 0xc5, 0x7c, 0xd6, 0x6f, 0x0e, 0xaf, 0x68, 0x34, 0xe5,
	0x0c, 0x84, 0xa3, 0x48, 0xbf, 0x0b, 0xb0, 0x97, 0x42, 0xd6, 0xe3, 0xe0, 0x76, 0x32, 0x40, 0x19,
	0x44, 0x7f, 0xc9, 0x52, 0xe1, 0x80, 0xe9, 0x2c, 0x81, 0x64, 0x85, 0xce, 0x24, 0x38, 0x49, 0x16,
	0x0b, 0xb5, 0x72, 0x90, 0x4b, 0x2c, 0x81, 0x64, 0x85, 0x2e, 0xfd, 0x29, 0x40, 0x23, 0xa3, 0x8d,
	0xbc, 0xe9, 0x7d, 0x94, 0x8c, 0x3f, 0x90, 0x37, 0x0b, 0x8e, 0x57, 0x74, 0x39, 0x83, 0x2d, 0xde,
	0xe0, 0x22, 0x83, 0xac, 0x6f, 0x94, 0x2e, 0x00, 0xf5, 0x70, 0x32, 0x4d, 0x66, 0xfe, 0x74, 0x18,
	0x85, 0x96, 0x37, 0x1f, 0x45, 0x5e, 0x1f, 0x45, 0xa8, 0xfa, 0xe3, 0xfe, 0x89, 0x70, 0x56, 0x6d,
	0xd7, 0x08, 0xfd, 0x29, 0xfd, 0x0c, 0x47, 0xa9, 0x3f, 0x3b, 0x48, 0xde, 0x05, 0x09, 0x09, 0x26,
	0x71, 0x14, 0x4e, 0x02, 0x7c, 0x09, 0x07, 0x49, 0xf6, 0x7b, 0x61, 0xc3, 0x9b, 0xe5, 0x86, 0xf3,
	0x28, 0x59, 0x62, 0xe3, 0x05, 0xec, 0xf8, 0xe3, 0x3e, 0xb7, 0x86, 0xbd, 0x74, 0x0d, 0x69, 0x8d,
	0xe4, 0xa0, 0x74, 0x0e, 0x5b, 0xca, 0xc3, 0x2c, 0x7c, 0xc4, 0x4f, 0xa0, 0x76, 0x3f, 0x1c, 0x05,
	0x6c, 0xc0, 0xe6, 0xda, 0x23, 0x65, 0x41, 0xfa, 0xb5, 0x02, 0x8d, 0xd4, 0xa1, 0xf5, 0x38, 0x28,
	0x4c, 0xde, 0xc2, 0x91, 0xbf, 0xc6, 0x7c, 0x66, 0xf5, 0x94, 0x4b, 0x7f, 0x91, 0x40, 0xd6, 0xb6,
	0xe1, 0x0d, 0xd4, 0xe3, 0xc7, 0x81, 0x19, 0x07, 0x09, 0xe7, 0x5b, 0x64, 0x2a, 0x56, 0x59, 0x27,
	0x3c, 0x09, 0xbb, 0x80, 0xc3, 0x95, 0x9c, 0xd9, 0xe7, 0x56, 0xbf, 0x79, 0xca, 0x5a, 0x57, 0xb7,
	0x81, 0xac, 0x69, 0xc1, 0x33, 0xd8, 0xf2, 0xd9, 0xda, 0x37, 0x59, 0x2f, 0xa4, 0xe6, 0x69, 0x85,
	0xa4, 0x80, 0xf4, 0xb7, 0x00, 0xcd, 0x2c, 0x83, 0x6c, 0xb3, 0x3f, 0x62, 0x10, 0x93, 0x7e, 0xbc,
	0x36, 0x08, 0x5b, 0xb5, 0xca, 0x20, 0x38, 0xd2, 0x07, 0x0b, 0x42, 0xda, 0x81, 0xad, 0x6f, 0x66,
	0x41, 0x32, 0x97, 0xe6, 0x20, 0xa6, 0x67, 0x3b, 0xbb, 0x5b, 0xe8, 0xb7, 0xf6, 0x02, 0xf6, 0xc9,
	0xff, 0xb8, 0x86, 0x16, 0x86, 0xd8, 0x86, 0x1a, 0x53, 0x56, 0xbd, 0xa9, 0x97, 0xdd, 0x42, 0x69,
	0xcc, 0xac, 0x4a, 0x4a, 0xf0, 0xf2, 0xaf, 0x4a, 0x3e, 0x77, 0xf9, 0xf5, 0xe3, 0x31, 0x34, 0xac,
	0xd7, 0x5d, 0xd7, 0x30, 0x1d, 0x57, 0x37, 0x6c, 0x47, 0xee, 0xf5, 0x34, 0x55, 0xdc, 0xc0, 0x06,
	0xec, 0xd3, 0x72, 0x59, 0x12, 0xf0, 0x29, 0x3c, 0xa1, 0xa5, 0x6f, 0x35, 0x62, 0xeb, 0xa6, 0xe1,
	0x2a, 0xaf, 0x64, 0xa3, 0xab, 0xa9, 0x62, 0x05, 0x4f, 0xe1, 0x98, 0x07, 0x0c, 0x33, 0xc3, 0xc4,
	0x6a, 0x0e, 0xdd, 0x19, 0x99, 0x90, 0x6b, 0xdf, 0x29, 0x8a, 0x66, 0xdb, 0xe2, 0x26, 0x9e, 0xc0,
	0xd1, 0x22, 0xd4, 0x91, 0x75, 0x3a, 0xd1, 0x56, 0x3e, 0xd1, 0x72, 0xcb, 0x36, 0x36, 0x01, 0x79,
	0x20, 0x6b, 0xd8, 0xc1, 0x3d, 0xd8, 0x4d, 0xeb, 0xba, 0x23, 0xee, 0xa2, 0x08, 0x7b, 0x74, 0xd4,
	0xd5, 0x1c, 0xb7, 0xa3, 0xf7, 0x34, 0xb1, 0x86, 0x5f, 0xc0, 0x39, 0xad, 0xa8, 0xe6, 0x77, 0x46,
	0xcf, 0x94, 0x55, 0x26, 0x40, 0xee, 0x14, 0x87, 0xba, 0xa5, 0x94, 0x62, 0x0a, 0xc0, 0x36, 0x7c,
	0xfe, 0x7e, 0x6a, 0x36, 0x69, 0xfd, 0xf2, 0x1f, 0xe1, 0x3f, 0xae, 0x37, 0x7c, 0x0e, 0x2d, 0xab,
	0x27, 0x3b, 0x1d, 0x93, 0xdc, 0xba, 0x72, 0x8f, 0x68, 0xb2, 0xfa, 0x66, 0x21, 0xdb, 0x16, 0x34,
	0x0b, 0x7c, 0x31, 0x77, 0x01, 0x2f, 0x40, 0x2a, 0x7b, 0x89, 0xa3, 0x77, 0x64, 0xc5, 0x29, 0xdd,
	0xe4, 0x3e, 0x2b, 0x78, 0x0e, 0x9f, 0xbd, 0x87, 0x97, 0x99, 0xac, 0xe2, 0xa7, 0xf0, 0xac, 0xa0,
	0xa9, 0x9a, 0xd5, 0x33, 0xdf, 0xdc, 0x6a, 0x86, 0xc3, 0xed, 0x02, 0xef, 0x95, 0x23, 0x14, 0x7b,
	0x41, 0xcf, 0x41, 0x8e, 0xb3, 0x7c, 0xb7, 0x2f, 0xbf, 0x86, 0x9d, 0xec, 0xc2, 0xc3, 0x1d, 0xa8,
	0x92, 0x3b, 0x43, 0xdc, 0x40, 0x80, 0x6d, 0xc5, 0x34, 0x3a, 0x7a, 0x57, 0x14, 0xf0, 0x00, 0x40,
	0xe9, 0x99, 0xb6, 0xe6, 0x2a, 0xa6, 0x61, 0x88, 0x15, 0xdc, 0x85, 0x4d, 0xdd, 0xe8, 0x98, 0x62,
	0xf5, 0xf2, 0x37, 0x01, 0xea, 0xdc, 0x9d, 0x83, 0x47, 0x20, 0xea, 0xb6, 0xbb, 0x78, 0xce, 0x36,
	0xf0, 0x10, 0xea, 0xf9, 0x0e, 0x5b, 0xaf, 0xa9, 0xe0, 0x29, 0x1c, 0x73, 0x05, 0xb7, 0x43, 0xcc,
	0xdb, 0x74, 0x67, 0x2b, 0xf8, 0x04, 0x0e, 0x33, 0x05, 0xf3, 0xce, 0x51, 0x65, 0x87, 0x2d, 0xba,
	0x01, 0xfb, 0xe5, 0xa9, 0xa2, 0x12, 0x9b, 0xf4, 0x4c, 0xd0, 0xf3, 0x60, 0x68, 0xdf, 0x3b, 0xac,
	0xb2, 0x75, 0xf9, 0x03, 0xd4, 0xb9, 0xaf, 0x9e, 0xcd, 0x61, 0xbb, 0xdc, 0x52, 0x4b, 0x3f, 0xcf,
	0xa1, 0x55, 0x04, 0xbb, 0x92, 0xb9, 0x28, 0x50, 0x0f, 0x69, 0x72, 0x05, 0x2a, 0x56, 0x6e, 0xfe,
	0x10, 0xa0, 0x6a, 0x85, 0x16, 0xbe, 0x84, 0x7a, 0x37, 0x98, 0x5a, 0x9e, 0xff, 0xe8, 0x0d, 0x82,
	0x09, 0x36, 0x56, 0x1e, 0xe5, 0x56, 0x33, 0xbd, 0x81, 0x96, 0x9f, 0x01, 0x69, 0xa3, 0x2d, 0x7c,
	0x29, 0xa0, 0x49, 0x5f, 0xbc, 0x61, 0x71, 0xc4, 0xd4, 0x20, 0x1e, 0x45, 0x73, 0x6c, 0xae, 0x7f,
	0x3a, 0x5b, 0xcf, 0x78, 0xad, 0xa5, 0xeb, 0x34, 0x15, 0x7c, 0xbb, 0xcd, 0xfe, 0x88, 0x7d, 0xf5,
	0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x80, 0x89, 0xa8, 0x34, 0xc4, 0x09, 0x00, 0x00,
}
