// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pnp.proto

/*
Package pnp is a generated protocol buffer package.

It is generated from these files:
	pnp.proto

It has these top-level messages:
	ClientInfo
	CommonClientInfo
	ClientPkgMsg
	ClientPlatformMsg
	InstructionPayload
	CommonServerResponse
	Chunk
	ServerPkgResponse
	ServerPlatformResponse
	Query
	ClientRequestMsg
*/
package pnp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "github.com/PnP/common/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ClientPkgMsgType int32

const (
	ClientPkgMsgType_PKG_INIT              ClientPkgMsgType = 0
	ClientPkgMsgType_PKG_NOT_INSTALLED     ClientPkgMsgType = 1
	ClientPkgMsgType_PKG_INSTALLED         ClientPkgMsgType = 2
	ClientPkgMsgType_PKG_VERSION_CHANGED   ClientPkgMsgType = 3
	ClientPkgMsgType_PKG_VERSION_NO_CHANGE ClientPkgMsgType = 4
	ClientPkgMsgType_PKG_UNINSTALL_SUCCESS ClientPkgMsgType = 5
	ClientPkgMsgType_PKG_UNINSTALL_FAILED  ClientPkgMsgType = 6
	ClientPkgMsgType_PKG_INSTALL_SUCCESS   ClientPkgMsgType = 7
	ClientPkgMsgType_PKG_INSTALL_FAILED    ClientPkgMsgType = 8
)

var ClientPkgMsgType_name = map[int32]string{
	0: "PKG_INIT",
	1: "PKG_NOT_INSTALLED",
	2: "PKG_INSTALLED",
	3: "PKG_VERSION_CHANGED",
	4: "PKG_VERSION_NO_CHANGE",
	5: "PKG_UNINSTALL_SUCCESS",
	6: "PKG_UNINSTALL_FAILED",
	7: "PKG_INSTALL_SUCCESS",
	8: "PKG_INSTALL_FAILED",
}
var ClientPkgMsgType_value = map[string]int32{
	"PKG_INIT":              0,
	"PKG_NOT_INSTALLED":     1,
	"PKG_INSTALLED":         2,
	"PKG_VERSION_CHANGED":   3,
	"PKG_VERSION_NO_CHANGE": 4,
	"PKG_UNINSTALL_SUCCESS": 5,
	"PKG_UNINSTALL_FAILED":  6,
	"PKG_INSTALL_SUCCESS":   7,
	"PKG_INSTALL_FAILED":    8,
}

func (x ClientPkgMsgType) String() string {
	return proto.EnumName(ClientPkgMsgType_name, int32(x))
}
func (ClientPkgMsgType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ClientPlatformMsgType int32

const (
	ClientPlatformMsgType_PLATFORM_INIT                      ClientPlatformMsgType = 0
	ClientPlatformMsgType_PLATFORM_ALREADY_INSTALLED         ClientPlatformMsgType = 1
	ClientPlatformMsgType_PLATFORM_NOT_INSTALLED             ClientPlatformMsgType = 2
	ClientPlatformMsgType_PLATFORM_ARTIFACT_DOWNLOAD_SUCCESS ClientPlatformMsgType = 3
	ClientPlatformMsgType_PLATFORM_ARTIFACT_DOWNLOAD_FAILED  ClientPlatformMsgType = 4
	ClientPlatformMsgType_PLATFORM_DEPLOYMENT_SUCCESS        ClientPlatformMsgType = 5
	ClientPlatformMsgType_PLATFORM_DEPLOYMENT_FAILED         ClientPlatformMsgType = 6
)

var ClientPlatformMsgType_name = map[int32]string{
	0: "PLATFORM_INIT",
	1: "PLATFORM_ALREADY_INSTALLED",
	2: "PLATFORM_NOT_INSTALLED",
	3: "PLATFORM_ARTIFACT_DOWNLOAD_SUCCESS",
	4: "PLATFORM_ARTIFACT_DOWNLOAD_FAILED",
	5: "PLATFORM_DEPLOYMENT_SUCCESS",
	6: "PLATFORM_DEPLOYMENT_FAILED",
}
var ClientPlatformMsgType_value = map[string]int32{
	"PLATFORM_INIT":                      0,
	"PLATFORM_ALREADY_INSTALLED":         1,
	"PLATFORM_NOT_INSTALLED":             2,
	"PLATFORM_ARTIFACT_DOWNLOAD_SUCCESS": 3,
	"PLATFORM_ARTIFACT_DOWNLOAD_FAILED":  4,
	"PLATFORM_DEPLOYMENT_SUCCESS":        5,
	"PLATFORM_DEPLOYMENT_FAILED":         6,
}

func (x ClientPlatformMsgType) String() string {
	return proto.EnumName(ClientPlatformMsgType_name, int32(x))
}
func (ClientPlatformMsgType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type CmdType int32

const (
	CmdType_RUN        CmdType = 0
	CmdType_CONFIG     CmdType = 1
	CmdType_INFO       CmdType = 2
	CmdType_CLOSE_CONN CmdType = 3
)

var CmdType_name = map[int32]string{
	0: "RUN",
	1: "CONFIG",
	2: "INFO",
	3: "CLOSE_CONN",
}
var CmdType_value = map[string]int32{
	"RUN":        0,
	"CONFIG":     1,
	"INFO":       2,
	"CLOSE_CONN": 3,
}

func (x CmdType) String() string {
	return proto.EnumName(CmdType_name, int32(x))
}
func (CmdType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type PkgOperType int32

const (
	PkgOperType_IS_PKG_INSTALLED      PkgOperType = 0
	PkgOperType_INSTALL_PKG           PkgOperType = 1
	PkgOperType_INSTALL_PKG_FROM_FILE PkgOperType = 2
	PkgOperType_IS_PKG_OUTDATED       PkgOperType = 3
	PkgOperType_UNINSTALL_PKG         PkgOperType = 4
	PkgOperType_GET_NEXT_PKG          PkgOperType = 5
)

var PkgOperType_name = map[int32]string{
	0: "IS_PKG_INSTALLED",
	1: "INSTALL_PKG",
	2: "INSTALL_PKG_FROM_FILE",
	3: "IS_PKG_OUTDATED",
	4: "UNINSTALL_PKG",
	5: "GET_NEXT_PKG",
}
var PkgOperType_value = map[string]int32{
	"IS_PKG_INSTALLED":      0,
	"INSTALL_PKG":           1,
	"INSTALL_PKG_FROM_FILE": 2,
	"IS_PKG_OUTDATED":       3,
	"UNINSTALL_PKG":         4,
	"GET_NEXT_PKG":          5,
}

func (x PkgOperType) String() string {
	return proto.EnumName(PkgOperType_name, int32(x))
}
func (PkgOperType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type SDPOperType int32

const (
	SDPOperType_IS_PLATFORM_INSTALLED      SDPOperType = 0
	SDPOperType_DOWNLOAD_PLATFORM_ARTIFACT SDPOperType = 1
	SDPOperType_DEPLOY_PLATFORM            SDPOperType = 2
)

var SDPOperType_name = map[int32]string{
	0: "IS_PLATFORM_INSTALLED",
	1: "DOWNLOAD_PLATFORM_ARTIFACT",
	2: "DEPLOY_PLATFORM",
}
var SDPOperType_value = map[string]int32{
	"IS_PLATFORM_INSTALLED":      0,
	"DOWNLOAD_PLATFORM_ARTIFACT": 1,
	"DEPLOY_PLATFORM":            2,
}

func (x SDPOperType) String() string {
	return proto.EnumName(SDPOperType_name, int32(x))
}
func (SDPOperType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type ClientInfo struct {
	OsType   string `protobuf:"bytes,1,opt,name=osType" json:"osType,omitempty"`
	OsFlavor string `protobuf:"bytes,2,opt,name=osFlavor" json:"osFlavor,omitempty"`
	ArchType string `protobuf:"bytes,3,opt,name=archType" json:"archType,omitempty"`
	ClientId string `protobuf:"bytes,4,opt,name=clientId" json:"clientId,omitempty"`
}

func (m *ClientInfo) Reset()                    { *m = ClientInfo{} }
func (m *ClientInfo) String() string            { return proto.CompactTextString(m) }
func (*ClientInfo) ProtoMessage()               {}
func (*ClientInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ClientInfo) GetOsType() string {
	if m != nil {
		return m.OsType
	}
	return ""
}

func (m *ClientInfo) GetOsFlavor() string {
	if m != nil {
		return m.OsFlavor
	}
	return ""
}

func (m *ClientInfo) GetArchType() string {
	if m != nil {
		return m.ArchType
	}
	return ""
}

func (m *ClientInfo) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

type CommonClientInfo struct {
	RequestHeader *common.RequestHeader `protobuf:"bytes,1,opt,name=requestHeader" json:"requestHeader,omitempty"`
	ClientInfo    *ClientInfo           `protobuf:"bytes,2,opt,name=clientInfo" json:"clientInfo,omitempty"`
}

func (m *CommonClientInfo) Reset()                    { *m = CommonClientInfo{} }
func (m *CommonClientInfo) String() string            { return proto.CompactTextString(m) }
func (*CommonClientInfo) ProtoMessage()               {}
func (*CommonClientInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CommonClientInfo) GetRequestHeader() *common.RequestHeader {
	if m != nil {
		return m.RequestHeader
	}
	return nil
}

func (m *CommonClientInfo) GetClientInfo() *ClientInfo {
	if m != nil {
		return m.ClientInfo
	}
	return nil
}

type ClientPkgMsg struct {
	CommonClientInfo *CommonClientInfo `protobuf:"bytes,1,opt,name=commonClientInfo" json:"commonClientInfo,omitempty"`
	ClientPkgMsgType ClientPkgMsgType  `protobuf:"varint,2,opt,name=clientPkgMsgType,enum=pnp.ClientPkgMsgType" json:"clientPkgMsgType,omitempty"`
}

func (m *ClientPkgMsg) Reset()                    { *m = ClientPkgMsg{} }
func (m *ClientPkgMsg) String() string            { return proto.CompactTextString(m) }
func (*ClientPkgMsg) ProtoMessage()               {}
func (*ClientPkgMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ClientPkgMsg) GetCommonClientInfo() *CommonClientInfo {
	if m != nil {
		return m.CommonClientInfo
	}
	return nil
}

func (m *ClientPkgMsg) GetClientPkgMsgType() ClientPkgMsgType {
	if m != nil {
		return m.ClientPkgMsgType
	}
	return ClientPkgMsgType_PKG_INIT
}

type ClientPlatformMsg struct {
	CommonClientInfo      *CommonClientInfo     `protobuf:"bytes,1,opt,name=commonClientInfo" json:"commonClientInfo,omitempty"`
	ClientPlatformMsgType ClientPlatformMsgType `protobuf:"varint,2,opt,name=clientPlatformMsgType,enum=pnp.ClientPlatformMsgType" json:"clientPlatformMsgType,omitempty"`
	Error                 string                `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
}

func (m *ClientPlatformMsg) Reset()                    { *m = ClientPlatformMsg{} }
func (m *ClientPlatformMsg) String() string            { return proto.CompactTextString(m) }
func (*ClientPlatformMsg) ProtoMessage()               {}
func (*ClientPlatformMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ClientPlatformMsg) GetCommonClientInfo() *CommonClientInfo {
	if m != nil {
		return m.CommonClientInfo
	}
	return nil
}

func (m *ClientPlatformMsg) GetClientPlatformMsgType() ClientPlatformMsgType {
	if m != nil {
		return m.ClientPlatformMsgType
	}
	return ClientPlatformMsgType_PLATFORM_INIT
}

func (m *ClientPlatformMsg) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type InstructionPayload struct {
	Cmd []string `protobuf:"bytes,1,rep,name=cmd" json:"cmd,omitempty"`
}

func (m *InstructionPayload) Reset()                    { *m = InstructionPayload{} }
func (m *InstructionPayload) String() string            { return proto.CompactTextString(m) }
func (*InstructionPayload) ProtoMessage()               {}
func (*InstructionPayload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *InstructionPayload) GetCmd() []string {
	if m != nil {
		return m.Cmd
	}
	return nil
}

type CommonServerResponse struct {
	ResponseHeader *common.ResponseHeader `protobuf:"bytes,1,opt,name=responseHeader" json:"responseHeader,omitempty"`
	CmdType        CmdType                `protobuf:"varint,2,opt,name=cmdType,enum=pnp.CmdType" json:"cmdType,omitempty"`
}

func (m *CommonServerResponse) Reset()                    { *m = CommonServerResponse{} }
func (m *CommonServerResponse) String() string            { return proto.CompactTextString(m) }
func (*CommonServerResponse) ProtoMessage()               {}
func (*CommonServerResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CommonServerResponse) GetResponseHeader() *common.ResponseHeader {
	if m != nil {
		return m.ResponseHeader
	}
	return nil
}

func (m *CommonServerResponse) GetCmdType() CmdType {
	if m != nil {
		return m.CmdType
	}
	return CmdType_RUN
}

type Chunk struct {
	FileChunk []byte `protobuf:"bytes,1,opt,name=fileChunk,proto3" json:"fileChunk,omitempty"`
}

func (m *Chunk) Reset()                    { *m = Chunk{} }
func (m *Chunk) String() string            { return proto.CompactTextString(m) }
func (*Chunk) ProtoMessage()               {}
func (*Chunk) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Chunk) GetFileChunk() []byte {
	if m != nil {
		return m.FileChunk
	}
	return nil
}

type ServerPkgResponse struct {
	CommonServerResponse *CommonServerResponse `protobuf:"bytes,1,opt,name=commonServerResponse" json:"commonServerResponse,omitempty"`
	PkgOperType          PkgOperType           `protobuf:"varint,2,opt,name=pkgOperType,enum=pnp.PkgOperType" json:"pkgOperType,omitempty"`
	InstructionPayload   *InstructionPayload   `protobuf:"bytes,3,opt,name=instructionPayload" json:"instructionPayload,omitempty"`
	Chunk                *Chunk                `protobuf:"bytes,4,opt,name=chunk" json:"chunk,omitempty"`
}

func (m *ServerPkgResponse) Reset()                    { *m = ServerPkgResponse{} }
func (m *ServerPkgResponse) String() string            { return proto.CompactTextString(m) }
func (*ServerPkgResponse) ProtoMessage()               {}
func (*ServerPkgResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ServerPkgResponse) GetCommonServerResponse() *CommonServerResponse {
	if m != nil {
		return m.CommonServerResponse
	}
	return nil
}

func (m *ServerPkgResponse) GetPkgOperType() PkgOperType {
	if m != nil {
		return m.PkgOperType
	}
	return PkgOperType_IS_PKG_INSTALLED
}

func (m *ServerPkgResponse) GetInstructionPayload() *InstructionPayload {
	if m != nil {
		return m.InstructionPayload
	}
	return nil
}

func (m *ServerPkgResponse) GetChunk() *Chunk {
	if m != nil {
		return m.Chunk
	}
	return nil
}

type ServerPlatformResponse struct {
	CommonServerResponse *CommonServerResponse `protobuf:"bytes,1,opt,name=commonServerResponse" json:"commonServerResponse,omitempty"`
	SdpOperType          SDPOperType           `protobuf:"varint,2,opt,name=sdpOperType,enum=pnp.SDPOperType" json:"sdpOperType,omitempty"`
	InstructionPayload   *InstructionPayload   `protobuf:"bytes,3,opt,name=instructionPayload" json:"instructionPayload,omitempty"`
}

func (m *ServerPlatformResponse) Reset()                    { *m = ServerPlatformResponse{} }
func (m *ServerPlatformResponse) String() string            { return proto.CompactTextString(m) }
func (*ServerPlatformResponse) ProtoMessage()               {}
func (*ServerPlatformResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ServerPlatformResponse) GetCommonServerResponse() *CommonServerResponse {
	if m != nil {
		return m.CommonServerResponse
	}
	return nil
}

func (m *ServerPlatformResponse) GetSdpOperType() SDPOperType {
	if m != nil {
		return m.SdpOperType
	}
	return SDPOperType_IS_PLATFORM_INSTALLED
}

func (m *ServerPlatformResponse) GetInstructionPayload() *InstructionPayload {
	if m != nil {
		return m.InstructionPayload
	}
	return nil
}

type Query struct {
}

func (m *Query) Reset()                    { *m = Query{} }
func (m *Query) String() string            { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()               {}
func (*Query) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type ClientRequestMsg struct {
	RequestHeader *common.RequestHeader `protobuf:"bytes,1,opt,name=RequestHeader" json:"RequestHeader,omitempty"`
	QueryData     *Query                `protobuf:"bytes,2,opt,name=QueryData" json:"QueryData,omitempty"`
}

func (m *ClientRequestMsg) Reset()                    { *m = ClientRequestMsg{} }
func (m *ClientRequestMsg) String() string            { return proto.CompactTextString(m) }
func (*ClientRequestMsg) ProtoMessage()               {}
func (*ClientRequestMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ClientRequestMsg) GetRequestHeader() *common.RequestHeader {
	if m != nil {
		return m.RequestHeader
	}
	return nil
}

func (m *ClientRequestMsg) GetQueryData() *Query {
	if m != nil {
		return m.QueryData
	}
	return nil
}

func init() {
	proto.RegisterType((*ClientInfo)(nil), "pnp.ClientInfo")
	proto.RegisterType((*CommonClientInfo)(nil), "pnp.CommonClientInfo")
	proto.RegisterType((*ClientPkgMsg)(nil), "pnp.ClientPkgMsg")
	proto.RegisterType((*ClientPlatformMsg)(nil), "pnp.ClientPlatformMsg")
	proto.RegisterType((*InstructionPayload)(nil), "pnp.InstructionPayload")
	proto.RegisterType((*CommonServerResponse)(nil), "pnp.CommonServerResponse")
	proto.RegisterType((*Chunk)(nil), "pnp.Chunk")
	proto.RegisterType((*ServerPkgResponse)(nil), "pnp.ServerPkgResponse")
	proto.RegisterType((*ServerPlatformResponse)(nil), "pnp.ServerPlatformResponse")
	proto.RegisterType((*Query)(nil), "pnp.Query")
	proto.RegisterType((*ClientRequestMsg)(nil), "pnp.ClientRequestMsg")
	proto.RegisterEnum("pnp.ClientPkgMsgType", ClientPkgMsgType_name, ClientPkgMsgType_value)
	proto.RegisterEnum("pnp.ClientPlatformMsgType", ClientPlatformMsgType_name, ClientPlatformMsgType_value)
	proto.RegisterEnum("pnp.CmdType", CmdType_name, CmdType_value)
	proto.RegisterEnum("pnp.PkgOperType", PkgOperType_name, PkgOperType_value)
	proto.RegisterEnum("pnp.SDPOperType", SDPOperType_name, SDPOperType_value)
}

func init() { proto.RegisterFile("pnp.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 962 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x4b, 0x6f, 0xdb, 0x46,
	0x10, 0x36, 0xf5, 0xf0, 0x63, 0xe4, 0x07, 0x35, 0xb1, 0x14, 0x5b, 0x29, 0x52, 0x97, 0x40, 0x0c,
	0x43, 0x07, 0xbb, 0x50, 0x2f, 0x05, 0x02, 0x04, 0x20, 0x48, 0x4a, 0x21, 0x2c, 0x91, 0xec, 0x92,
	0x6e, 0x9b, 0x43, 0x41, 0x30, 0x14, 0x2d, 0x0b, 0x92, 0x48, 0x96, 0x92, 0x82, 0xea, 0x52, 0xb4,
	0xc7, 0x5e, 0x8b, 0xfe, 0x9e, 0xfe, 0x9a, 0xfc, 0x86, 0x9e, 0x0b, 0x2e, 0x5f, 0xab, 0x07, 0x0a,
	0x14, 0x48, 0x6e, 0x9a, 0xf9, 0xbe, 0x99, 0xfd, 0xf6, 0xdb, 0xdd, 0xa1, 0xe0, 0x28, 0xf4, 0xc3,
	0xdb, 0x30, 0x0a, 0x16, 0x01, 0x96, 0x43, 0x3f, 0x6c, 0xdd, 0x8c, 0xc6, 0x8b, 0xa7, 0xe5, 0xfb,
	0x5b, 0x37, 0x98, 0xdd, 0x19, 0xbe, 0x71, 0xe7, 0x06, 0xb3, 0x59, 0xe0, 0xdf, 0x51, 0x46, 0x1a,
	0x24, 0x74, 0xe1, 0x17, 0x00, 0x69, 0x3a, 0xf6, 0xfc, 0x85, 0xea, 0x3f, 0x06, 0xd8, 0x84, 0xfd,
	0x60, 0x6e, 0xad, 0x42, 0xef, 0x82, 0xbb, 0xe2, 0x6e, 0x8e, 0x48, 0x1a, 0x61, 0x0b, 0x0e, 0x83,
	0x79, 0x77, 0xea, 0x7c, 0x08, 0xa2, 0x8b, 0x12, 0x45, 0xf2, 0x38, 0xc6, 0x9c, 0xc8, 0x7d, 0xa2,
	0x55, 0xe5, 0x04, 0xcb, 0xe2, 0x18, 0x73, 0x93, 0xee, 0xc3, 0x8b, 0x4a, 0x82, 0x65, 0xb1, 0xf0,
	0x1b, 0x07, 0xbc, 0x44, 0xa5, 0x30, 0x02, 0x5e, 0xc3, 0x49, 0xe4, 0xfd, 0xbc, 0xf4, 0xe6, 0x8b,
	0xb7, 0x9e, 0x33, 0xf4, 0x22, 0xaa, 0xa3, 0xd6, 0x69, 0xdc, 0xa6, 0xa2, 0x09, 0x0b, 0x92, 0x75,
	0x2e, 0xde, 0x01, 0xb8, 0x79, 0x2b, 0xaa, 0xb3, 0xd6, 0x39, 0xbb, 0x8d, 0xad, 0x29, 0x56, 0x20,
	0x0c, 0x45, 0xf8, 0x8b, 0x83, 0xe3, 0x04, 0x32, 0x26, 0xa3, 0xc1, 0x7c, 0x84, 0x22, 0xf0, 0xee,
	0x86, 0xa4, 0x5c, 0x01, 0xed, 0xb3, 0x01, 0x92, 0x2d, 0x3a, 0x6d, 0xc1, 0xb4, 0xa4, 0xb6, 0xc4,
	0x52, 0x4e, 0xb3, 0x16, 0x1b, 0x20, 0xd9, 0xa2, 0x0b, 0x7f, 0x73, 0x50, 0x4f, 0x69, 0x53, 0x67,
	0xf1, 0x18, 0x44, 0xb3, 0x4f, 0xa4, 0xcd, 0x80, 0x86, 0xbb, 0xd9, 0x97, 0x11, 0xd8, 0x62, 0x05,
	0xae, 0x33, 0xc8, 0xee, 0x42, 0x3c, 0x87, 0xaa, 0x17, 0x45, 0x41, 0x94, 0x9e, 0x7c, 0x12, 0x08,
	0xd7, 0x80, 0xaa, 0x3f, 0x5f, 0x44, 0x4b, 0x77, 0x31, 0x0e, 0x7c, 0xc3, 0x59, 0x4d, 0x03, 0x67,
	0x88, 0x3c, 0x94, 0xdd, 0xd9, 0xf0, 0x82, 0xbb, 0x2a, 0xdf, 0x1c, 0x91, 0xf8, 0xa7, 0xf0, 0x2b,
	0x9c, 0x27, 0xaa, 0x4d, 0x2f, 0xfa, 0xe0, 0x45, 0xc4, 0x9b, 0x87, 0x81, 0x3f, 0xf7, 0xf0, 0x0d,
	0x9c, 0x46, 0xe9, 0xef, 0xb5, 0x6b, 0xd0, 0x2c, 0xae, 0x01, 0x8b, 0x92, 0x0d, 0x36, 0x5e, 0xc3,
	0x81, 0x3b, 0x1b, 0x32, 0x3b, 0x3b, 0x4e, 0x76, 0x96, 0xe4, 0x48, 0x06, 0x0a, 0xaf, 0xa0, 0x2a,
	0x3d, 0x2d, 0xfd, 0x09, 0x7e, 0x01, 0x47, 0x8f, 0xe3, 0xa9, 0x47, 0x03, 0xba, 0xd6, 0x31, 0x29,
	0x12, 0xc2, 0xef, 0x25, 0xa8, 0x27, 0x0a, 0x8d, 0xc9, 0x28, 0x17, 0x39, 0x80, 0x73, 0x77, 0x87,
	0xf8, 0x54, 0xea, 0x25, 0x73, 0x26, 0xeb, 0x04, 0xb2, 0xb3, 0x0c, 0x3b, 0x50, 0x0b, 0x27, 0x23,
	0x3d, 0xf4, 0x22, 0x46, 0x37, 0x4f, 0xbb, 0x18, 0x45, 0x9e, 0xb0, 0x24, 0xec, 0x01, 0x8e, 0xb7,
	0x7c, 0xa6, 0x47, 0x51, 0xeb, 0x3c, 0xa7, 0xa5, 0xdb, 0xc7, 0x40, 0x76, 0x94, 0xe0, 0x15, 0x54,
	0x5d, 0xba, 0xf7, 0x0a, 0xad, 0x85, 0x44, 0x7c, 0x9c, 0x21, 0x09, 0x20, 0x7c, 0xe4, 0xa0, 0x99,
	0x7a, 0x90, 0x5e, 0x81, 0xcf, 0x68, 0xc4, 0x7c, 0x18, 0xee, 0x34, 0xc2, 0x94, 0x8d, 0xc2, 0x08,
	0x86, 0xf4, 0xc9, 0x8c, 0x10, 0x0e, 0xa0, 0xfa, 0xdd, 0xd2, 0x8b, 0x56, 0xc2, 0x0a, 0xf8, 0xe4,
	0x21, 0xa4, 0x13, 0x27, 0x7e, 0x81, 0xaf, 0xe1, 0x84, 0xfc, 0x8f, 0xe1, 0xb4, 0x16, 0xe2, 0x0d,
	0x1c, 0xd1, 0xce, 0xb2, 0xb3, 0x70, 0xd2, 0xd9, 0x94, 0xd8, 0x4c, 0xb3, 0xa4, 0x00, 0xdb, 0x1f,
	0xb9, 0x6c, 0xed, 0x62, 0x26, 0xe0, 0x31, 0x1c, 0x1a, 0xf7, 0x3d, 0x5b, 0xd5, 0x54, 0x8b, 0xdf,
	0xc3, 0x06, 0xd4, 0xe3, 0x48, 0xd3, 0x2d, 0x5b, 0xd5, 0x4c, 0x4b, 0xec, 0xf7, 0x15, 0x99, 0xe7,
	0xb0, 0x0e, 0x27, 0x09, 0x29, 0x4b, 0x95, 0xf0, 0x39, 0x3c, 0x8b, 0x53, 0xdf, 0x2b, 0xc4, 0x54,
	0x75, 0xcd, 0x96, 0xde, 0x8a, 0x5a, 0x4f, 0x91, 0xf9, 0x32, 0x5e, 0x42, 0x83, 0x05, 0x34, 0x3d,
	0xc5, 0xf8, 0x4a, 0x06, 0x3d, 0x68, 0x69, 0x23, 0xdb, 0x7c, 0x90, 0x24, 0xc5, 0x34, 0xf9, 0x2a,
	0x5e, 0xc0, 0xf9, 0x3a, 0xd4, 0x15, 0xd5, 0x78, 0xa1, 0xfd, 0x6c, 0xa1, 0xcd, 0x92, 0x03, 0x6c,
	0x02, 0xb2, 0x40, 0x5a, 0x70, 0xd8, 0xfe, 0x87, 0x83, 0xc6, 0xce, 0x59, 0x43, 0xb7, 0xd1, 0x17,
	0xad, 0xae, 0x4e, 0x06, 0xd9, 0x86, 0x5f, 0x42, 0x2b, 0x4f, 0x89, 0x7d, 0xa2, 0x88, 0xf2, 0xbb,
	0xb5, 0x9d, 0xb7, 0xa0, 0x99, 0xe3, 0xeb, 0xae, 0x94, 0xf0, 0x1a, 0x84, 0xa2, 0x96, 0x58, 0x6a,
	0x57, 0x94, 0x2c, 0x5b, 0xd6, 0x7f, 0xd0, 0xfa, 0xba, 0x28, 0xe7, 0x42, 0xcb, 0xf8, 0x0a, 0xbe,
	0xfa, 0x0f, 0x5e, 0xaa, 0xbb, 0x82, 0x5f, 0xc2, 0x8b, 0x9c, 0x26, 0x2b, 0x46, 0x5f, 0x7f, 0x37,
	0x50, 0x34, 0x8b, 0xf1, 0x88, 0xd5, 0xca, 0x10, 0x32, 0xa7, 0xda, 0xdf, 0xc2, 0x41, 0x3a, 0x89,
	0xf0, 0x00, 0xca, 0xe4, 0x41, 0xe3, 0xf7, 0x10, 0x60, 0x5f, 0xd2, 0xb5, 0xae, 0xda, 0xe3, 0x39,
	0x3c, 0x84, 0x8a, 0xaa, 0x75, 0x75, 0xbe, 0x84, 0xa7, 0x00, 0x52, 0x5f, 0x37, 0x15, 0x5b, 0xd2,
	0x35, 0x8d, 0x2f, 0xb7, 0xff, 0xe0, 0xa0, 0xc6, 0x0c, 0x03, 0x3c, 0x07, 0x5e, 0x35, 0xed, 0xf5,
	0x23, 0xdf, 0xc3, 0x33, 0xa8, 0x65, 0x66, 0x1b, 0xf7, 0x71, 0xc3, 0x4b, 0x68, 0x30, 0x09, 0xbb,
	0x4b, 0xf4, 0x81, 0xdd, 0x55, 0xfb, 0x0a, 0x5f, 0xc2, 0x67, 0x70, 0x96, 0x76, 0xd0, 0x1f, 0x2c,
	0x59, 0xb4, 0xe8, 0xd5, 0xa8, 0xc3, 0x49, 0x71, 0xc0, 0x71, 0x8b, 0x0a, 0xf2, 0x70, 0xdc, 0x53,
	0x2c, 0x5b, 0x53, 0x7e, 0xb4, 0x68, 0xa6, 0xda, 0xfe, 0x09, 0x6a, 0xcc, 0x73, 0xa4, 0x6b, 0x98,
	0x36, 0x73, 0x6c, 0x85, 0x9e, 0x97, 0xd0, 0xca, 0x5d, 0xdc, 0x32, 0x98, 0xe7, 0x62, 0x0d, 0x89,
	0x4d, 0x39, 0xca, 0x97, 0x3a, 0x7f, 0x72, 0x50, 0x36, 0x7c, 0x03, 0xdf, 0x40, 0xad, 0xe7, 0x2d,
	0x0c, 0xc7, 0x9d, 0x38, 0x23, 0x6f, 0x8e, 0xf5, 0xad, 0x6f, 0x68, 0xab, 0x99, 0x8c, 0x86, 0xcd,
	0xf9, 0x2c, 0xec, 0xdd, 0x70, 0x5f, 0x73, 0x78, 0x0f, 0xa7, 0xb2, 0x17, 0x4e, 0x83, 0x55, 0x76,
	0xc9, 0xb0, 0xb9, 0xfb, 0x2b, 0xd7, 0x7a, 0xc1, 0xf6, 0xd9, 0x98, 0x71, 0x49, 0xb3, 0xf7, 0xfb,
	0xf4, 0x3f, 0xd3, 0x37, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xd7, 0x03, 0xa9, 0x52, 0x6f, 0x09,
	0x00, 0x00,
}
